### ISSUE TITLE
regarding response performance

### ISSUE THREAD

**Issue by revolunet** [marcuswestin/WebViewProxy#11]
Hey, thanks for this very interesting work, i'm playing with it in the context of a cordova app :)

For some reason, responding with a 650k image takes 150ms on an iPad Air :

Is this "normal" ? and do you have any idea how to speed this up ? the image is already loaded in memory (comes from SDWebImage)

The part which takes time is `[res respondWithImage:image];`

https://github.com/revolunet/cordova-plugin-sdwebimage-test/blob/master/cordova/plugins/cordova-plugin-sdwebimage/src/ios/CDVSDWebImage.m#L17-L46

thanks :)

**Comment by marcuswestin** [comment]
Apologies for the late response. I haven't done any work on measuring or ensuring performance.

If you create a PR with an example app that exhibits the problematic behavior then that will be a good place to start getting help on this.

Cheers, and thanks for the report!
Marcus

**Comment by marcuswestin** [comment]
Closing for now. Feel free to reopen with more info!
