### ISSUE TITLE
WKWebView support

### ISSUE THREAD

**Issue by cerupcat** [marcuswestin/WebViewProxy#15]
From what I can tell, this doesn't currently work with WKWebView. Is there a way to integrate this with WKWebView or do you know of other options (frameworks) for this?

**Comment by zkrige** [comment]
http://stackoverflow.com/questions/24208229/wkwebview-and-nsurlprotocol-not-working

`As of iOS 9.3 SDK, WKWebView is still unable to make use of custom NSURLProtocols.`

so currently, there isnt really anything that can be done

**Comment by marcuswestin** [comment]
Closing as wontfix. Feel free to reopen with more info.
