### ISSUE TITLE
all requests go through the proxy server

### ISSUE THREAD

**Issue by yinyinliushang** [marcuswestin/WebViewProxy#9]
I use the following code to let all the http request go through the proxy server,while in iPad or iPhone the web pages are PC pages,that is to say,it doesn't invoke the iOS pages,why?
Another question is that the video doesn't go through the proxy server.
<addr>\- (void)viewDidLoad
{
    [super viewDidLoad];
    NSURL _url = [NSURL URLWithString:@"http://m.letv.com"];
    [self setupProxy];
    [self.trafficFilteringWebView loadRequest:[NSURLRequest requestWithURL:url]];
}
<addr>\- (void) setupProxy
{
    NSOperationQueue_ queue = [[NSOperationQueue alloc] init];
    [queue setMaxConcurrentOperationCount:5];
    [WebViewProxy handleRequestsWithScheme:@"http" handler:^(NSURLRequest *req, WVPResponse *res){
        __weak ASIHTTPRequest *request=[ASIHTTPRequest requestWithURL:req.URL];
        [request setDelegate:self];
 //       [request setUserAgentString:@"mozilla/5.0 (iphone; cpu iphone os 7_0_2 like mac os x) applewebkit/537.51.1 (khtml, like gecko) version/7.0 mobile/11a501 safari/9537.53"];
//        [request setUserAgentString:@"Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5355d Safari/8536.25"];
        [request setProxyHost:@"12.46.6.98"];
        [request setProxyPort:3128];
        [request setCompletionBlock:^{
            [NSURLConnection connectionWithRequest:req delegate:res];
        }];
        [request setFailedBlock:^{}];
        [request startAsynchronous];
    }];
}

**Comment by ffzzqq1128** [comment]
Are you kidding me?ASI is subclass of NSOperation no subclass of NSURLRequest. you can build success?
